#ifndef TURBOQUANT_H
#define TURBOQUANT_H

/* Auto-generated by cbindgen from turboquant-ffi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Operation completed successfully.
#define TQ_OK 0

// A required pointer argument was NULL.
#define TQ_ERR_NULL_POINTER 1

// An argument value was invalid (bad enum value, out-of-range parameter,
// zero-length input, non-finite float, ...).
#define TQ_ERR_INVALID_ARGUMENT 2

// An output buffer capacity was too small. Use `tq_packed_size` /
// `tq_corr_size` to size buffers.
#define TQ_ERR_BUFFER_TOO_SMALL 3

// An internal error occurred (should not happen for valid inputs).
#define TQ_ERR_INTERNAL 4

// Scale = max(|x|) of the block (`scale_param` is ignored).
#define TQ_SCALE_ABSMAX 0

// Scale = the `scale_param`-th percentile of |x|; `scale_param` must be in
// [0.0, 1.0].
#define TQ_SCALE_PERCENTILE 1

// Scale = standard deviation of the block (`scale_param` is ignored).
#define TQ_SCALE_ADAPTIVE 2

// Scale = `scale_param` (must be finite and > 0).
#define TQ_SCALE_FIXED 3

// Opaque quantizer handle. Create with `tq_quantizer_create`, release with
// `tq_quantizer_destroy`. The handle is immutable after creation and safe
// to share across threads for concurrent `tq_quantize` / `tq_dequantize`
// calls.
typedef struct tq_quantizer tq_quantizer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Returns the `TurboQuant` version as a static NUL-terminated UTF-8 string.
// The returned pointer is valid for the lifetime of the program and must
// not be freed.
const char *tq_version(void);

// Returns the number of bytes of packed output produced when quantizing
// `n` float values (`n` is padded up to a multiple of 8 values; 3 bits per
// value). Returns 0 if `n` is 0 or unrepresentably large.
size_t tq_packed_size(size_t n);

// Returns the number of bytes of correction output produced when quantizing
// `n` float values with correction enabled (1 bit per value). Returns 0 if
// `n` is 0.
size_t tq_corr_size(size_t n);

// Creates a quantizer and stores the handle in `*out_quantizer`.
//
// - `bits`: bits per value; only 3 is currently supported.
// - `block_size`: nominal block size stored in the configuration. Each
//   `tq_quantize` call quantizes its entire input as one block with one
//   scale, so callers chunk their data and typically pass `block_size`
//   values per call.
// - `scale_mode`: one of `TQ_SCALE_ABSMAX`, `TQ_SCALE_PERCENTILE`,
//   `TQ_SCALE_ADAPTIVE`, `TQ_SCALE_FIXED`.
// - `scale_param`: percentile in `[0, 1]` for `TQ_SCALE_PERCENTILE`, fixed
//   scale (> 0) for `TQ_SCALE_FIXED`, ignored otherwise.
// - `correction_enabled`: non-zero enables 1-bit residual correction.
// - `correction_scale`: correction magnitude relative to the block scale
//   (a quarter step, 0.25/3.5 ≈ 0.0714, is the MSE-optimal fixed value —
//   see `turboquant_core::qjl::DEFAULT_CORRECTION_SCALE`); must be finite
//   and >= 0 when correction is enabled,
//   ignored otherwise.
//
// Returns `TQ_OK` and a non-NULL `*out_quantizer` on success. On failure,
// `*out_quantizer` is left untouched.
//
// # Safety
//
// `out_quantizer` must be NULL or a valid pointer to writable storage for
// one `tq_quantizer*`.
int tq_quantizer_create(uint8_t bits,
                        size_t block_size,
                        int scale_mode,
                        float scale_param,
                        int correction_enabled,
                        float correction_scale,
                        struct tq_quantizer **out_quantizer);

// Destroys a quantizer created with `tq_quantizer_create`. Passing NULL is
// a safe no-op. The handle must not be used after this call.
//
// # Safety
//
// `quantizer` must be NULL or a pointer previously returned by
// `tq_quantizer_create` that has not already been destroyed.
void tq_quantizer_destroy(struct tq_quantizer *quantizer);

// Quantizes `n` float values as a single block.
//
// - `input`: `n` finite float values (`n` > 0).
// - `packed_out` / `packed_cap`: output buffer for the packed 3-bit data;
//   `packed_cap` must be >= `tq_packed_size(n)`.
// - `packed_written`: receives the number of packed bytes written.
// - `scale_out`: receives the block scale (round-trips through f16).
// - `corr_out` / `corr_cap`: output buffer for the 1-bit correction data;
//   required (>= `tq_corr_size(n)`) when the quantizer was created with
//   correction enabled, ignored (may be NULL) otherwise.
// - `corr_written`: optional (may be NULL); receives the number of
//   correction bytes written (0 when correction is disabled).
//
// Returns `TQ_OK` on success.
//
// # Safety
//
// All non-NULL pointers must be valid for the accesses implied by the
// documented sizes: `input` readable for `n` floats, `packed_out` writable
// for `packed_cap` bytes, `corr_out` writable for `corr_cap` bytes,
// `packed_written`, `scale_out` and `corr_written` writable.
int tq_quantize(const struct tq_quantizer *quantizer,
                const float *input,
                size_t n,
                uint8_t *packed_out,
                size_t packed_cap,
                size_t *packed_written,
                float *scale_out,
                uint8_t *corr_out,
                size_t corr_cap,
                size_t *corr_written);

// Dequantizes a block previously produced by `tq_quantize` back to `n`
// float values.
//
// - `packed` / `packed_len`: the packed 3-bit data;
//   `packed_len` must be >= `tq_packed_size(n)`.
// - `n`: the original number of values (> 0).
// - `scale`: the block scale returned by `tq_quantize`; it must remain finite
//   and non-zero after conversion to the core's binary16 scale representation.
// - `corr` / `corr_len`: optional correction data; when `corr` is non-NULL,
//   `corr_len` must be >= `tq_corr_size(n)`. Correction is applied only if
//   the quantizer was created with correction enabled; passing NULL skips
//   correction.
// - `output` / `output_cap`: output buffer; `output_cap` must be >= `n`
//   floats.
//
// Returns `TQ_OK` on success.
//
// # Safety
//
// All non-NULL pointers must be valid for the accesses implied by the
// documented sizes: `packed` readable for `packed_len` bytes, `corr`
// readable for `corr_len` bytes, `output` writable for `output_cap` floats.
int tq_dequantize(const struct tq_quantizer *quantizer,
                  const uint8_t *packed,
                  size_t packed_len,
                  size_t n,
                  float scale,
                  const uint8_t *corr,
                  size_t corr_len,
                  float *output,
                  size_t output_cap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* TURBOQUANT_H */
